mod common;
mod test_compress_constants;
mod test_constant_optimization_birth_reset;
mod test_equation_search_runs;
mod test_frequency_in_tournament;
mod test_loss;
mod test_next_generation_retry_and_skip;
mod test_population_replacement;
